/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosServicesRouteImport } from './routes/nos-services'
import { Route as NosProduitsRouteImport } from './routes/nos-produits'
import { Route as DemanderUnDevisRouteImport } from './routes/demander-un-devis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const NosServicesRoute = NosServicesRouteImport.update({
  id: '/nos-services',
  path: '/nos-services',
  getParentRoute: () => rootRouteImport,
} as any)
const NosProduitsRoute = NosProduitsRouteImport.update({
  id: '/nos-produits',
  path: '/nos-produits',
  getParentRoute: () => rootRouteImport,
} as any)
const DemanderUnDevisRoute = DemanderUnDevisRouteImport.update({
  id: '/demander-un-devis',
  path: '/demander-un-devis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demander-un-devis': typeof DemanderUnDevisRoute
  '/nos-produits': typeof NosProduitsRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demander-un-devis': typeof DemanderUnDevisRoute
  '/nos-produits': typeof NosProduitsRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demander-un-devis': typeof DemanderUnDevisRoute
  '/nos-produits': typeof NosProduitsRoute
  '/nos-services': typeof NosServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demander-un-devis'
    | '/nos-produits'
    | '/nos-services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/demander-un-devis' | '/nos-produits' | '/nos-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demander-un-devis'
    | '/nos-produits'
    | '/nos-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemanderUnDevisRoute: typeof DemanderUnDevisRoute
  NosProduitsRoute: typeof NosProduitsRoute
  NosServicesRoute: typeof NosServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nos-services': {
      id: '/nos-services'
      path: '/nos-services'
      fullPath: '/nos-services'
      preLoaderRoute: typeof NosServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-produits': {
      id: '/nos-produits'
      path: '/nos-produits'
      fullPath: '/nos-produits'
      preLoaderRoute: typeof NosProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demander-un-devis': {
      id: '/demander-un-devis'
      path: '/demander-un-devis'
      fullPath: '/demander-un-devis'
      preLoaderRoute: typeof DemanderUnDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemanderUnDevisRoute: DemanderUnDevisRoute,
  NosProduitsRoute: NosProduitsRoute,
  NosServicesRoute: NosServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
